version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /filtering_index_vcf_files.wdl
    readMePath: /README.md
    authors:
      - name: Shahzad Ahmad
        email: shahzad.ahmad@well.ox.ac.uk
